### ISSUE TITLE
Passing autoformat as boot parameter causes kernel panic

### ISSUE THREAD

**Issue by bachp** [rancher/os#1243]
**RancherOS Version: 0.6.1**

**Where are you running RancherOS? (bare-metal and virtualbox)**

When passing the following parameters `rancher.state.dev=LABEL=RANCHER_STATE rancher.state.autoformat=[/dev/sda]` at boot time with an empty `/dev/sda` I get a kernel panic.

I tried multiple bare-metal machines and a VirtualBox VM using PXE as described [in the manual](http://docs.rancher.com/os/running-rancheros/server/pxe/).

Here is the panic message from the VirtualBox VM.
![image](https://cloud.githubusercontent.com/assets/333807/18610931/47be4354-7d2a-11e6-937e-7d6ed638d040.png)

The issue only occurs if an autoformat takes place. It doesn't happen if the state partition is already there and it doesn't happen either if the `rancher.state.dev=LABEL=RANCHER_STATE` parameter is omitted.

**Comment by joshwget** [comment]
It looks like the PXE docs were missing the `rancher.state.formatzero` flag. I updated the page to include this. If you add this flag to your setup then this should resolve the issue for you.

At the same time, it's definitely a bug that a kernel panic happens in this scenario.

**Comment by bachp** [comment]
@joshwget Thanks I will give it a try

**Comment by bachp** [comment]
@joshwget After adding `rancher.state.formatzero` I'm still getting the kernel panic.

**Comment by joshwget** [comment]
Is the device in `rancher.state.autoformat` wrong perhaps? This was something I accidentally did when I was testing this yesterday.

**Comment by bachp** [comment]
I used
```
rancher.state.dev=LABEL=RANCHER_STATE rancher.state.autoformat=[/dev/sda] rancher.state.formatzero rancher.cloud_init.datasources=['url:http://ipxe.lan/cloud-config']
```

If I boot with only 
```
rancher.cloud_init.datasources=['url:http://ipxe.lan/cloud-config']
```
and then access `/dev/sda` I can see it and it contains no partitions or filesystems (I used `wipefs` before)

**Comment by joshwget** [comment]
The kernel panic here should be fixed by #1252. In v0.7.0 it's likely that state will still fail to be mounted, but at least we'll be able to boot RancherOS running from memory. This will make it easier to troubleshoot.

If you'd like, you can try this out with v0.7.0-rc2.

**Comment by ChromoX** [comment]
I'm having this exact issue.

**Comment by joshwget** [comment]
@ChromoX It's on our [releases page](https://github.com/rancher/os/releases).

**Comment by ChromoX** [comment]
Is there anyway to hook this up to iPXE easily? iPXE doesn't seem to support https urls.

**Comment by joshwget** [comment]
Github supports HTTP for downloads, so you can just switch it to `http://` for testing.

**Comment by ChromoX** [comment]
Github sends a HTTP 302, which seems to force a redirect to https which iPXE fails on. I guess I'll have to stand up a HTTP server.

**Comment by ChromoX** [comment]
So I have RancherOS 0.7.0-rc2 loading up, but autoformat doesn't seem to work. 

My cloud-config contains:
```
rancher:
  state:
    fstype: auth
    formatzero: true
    dev: LABEL=RANCHER_STATE
    autoformat:
      - /dev/sda
      - /dev/sdb
```

```
[root@compute3 ~]# sudo system-docker ps -a
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS                        PORTS               NAMES
83058ba4a310        rancher/os-preload:v0.7.0-rc2     "/usr/bin/ros entrypo"   27 minutes ago      Exited (0) 27 minutes ago                         preload-user-images
59f7da69a58a        rancher/os-docker:1.12.1          "/usr/bin/user-docker"   27 minutes ago      Up 27 minutes                                     docker
35ca66d9b57d        rancher/os-console:v0.7.0-rc2     "/usr/bin/ros entrypo"   27 minutes ago      Up 27 minutes                                     console
be460fbede0b        rancher/os-base:v0.7.0-rc2        "/usr/bin/ros entrypo"   27 minutes ago      Up 27 minutes                                     network
495dd5a86c10        rancher/os-base:v0.7.0-rc2        "/usr/bin/ros entrypo"   27 minutes ago      Exited (0) 27 minutes ago                         cloud-init-execute
43fb3dd490a8        rancher/os-cloudinit:v0.7.0-rc2   "/usr/bin/ros entrypo"   27 minutes ago      Exited (0) 27 minutes ago                         cloud-init
dfaf74ef3dec        rancher/os-base:v0.7.0-rc2        "/usr/bin/ros entrypo"   27 minutes ago      Up 27 minutes                                     ntp
80d5347f6f30        rancher/os-base:v0.7.0-rc2        "/usr/bin/ros entrypo"   27 minutes ago      Exited (143) 27 minutes ago                       network-pre
592b57e97180        rancher/os-cloudinit:v0.7.0-rc2   "/usr/bin/ros entrypo"   27 minutes ago      Exited (0) 27 minutes ago                         cloud-init-pre
5c0f91e5ee83        rancher/os-udev:v0.7.0-rc2        "/usr/bin/ros entrypo"   27 minutes ago      Up 27 minutes                                     udev
dac1c4bdf3c9        rancher/os-base:v0.7.0-rc2        "/usr/bin/ros entrypo"   27 minutes ago      Created                                           all-volumes
861bfe67f341        rancher/os-udev:v0.7.0-rc2        "/usr/bin/ros entrypo"   27 minutes ago      Exited (0) 27 minutes ago                         udev-cold
38c9e425f4f8        rancher/os-preload:v0.7.0-rc2     "/usr/bin/ros entrypo"   27 minutes ago      Exited (0) 27 minutes ago                         preload-system-images
980aafc6557b        rancher/os-acpid:v0.7.0-rc2       "/usr/bin/ros entrypo"   27 minutes ago      Up 27 minutes                                     acpid
d944fb996a68        rancher/os-syslog:v0.7.0-rc2      "/usr/bin/ros entrypo"   27 minutes ago      Up 27 minutes                                     syslog
134335746e22        rancher/os-base:v0.7.0-rc2        "/usr/bin/ros entrypo"   27 minutes ago      Created                                           container-data-volumes
c1e620e19aa1        rancher/os-base:v0.7.0-rc2        "/usr/bin/ros entrypo"   27 minutes ago      Created                                           user-volumes
8207cdd8d2cc        rancher/os-base:v0.7.0-rc2        "/usr/bin/ros entrypo"   27 minutes ago      Created                                           system-volumes
d6ddbde3be18        rancher/os-base:v0.7.0-rc2        "/usr/bin/ros entrypo"   27 minutes ago      Created                                           command-volumes
```

Images:

```
[root@compute3 ~]# sudo system-docker images
REPOSITORY               TAG                 IMAGE ID            CREATED             SIZE
rancher/os-console       v0.7.0-rc2          10721c426834        4 days ago          25.52 MB
rancher/os-udev          v0.7.0-rc2          68d6ea8fe83f        5 days ago          25.51 MB
rancher/os-syslog        v0.7.0-rc2          953158db3d0b        5 days ago          25.51 MB
rancher/os-statescript   v0.7.0-rc2          7d58f531dea7        5 days ago          25.51 MB
rancher/os-preload       v0.7.0-rc2          c22e22148a3c        5 days ago          25.51 MB
rancher/os-cloudinit     v0.7.0-rc2          3c9eae2aa014        5 days ago          25.51 MB
rancher/os-autoformat    v0.7.0-rc2          498c83fc5816        5 days ago          25.51 MB
rancher/os-acpid         v0.7.0-rc2          b8f764b533d1        5 days ago          25.51 MB
rancher/os-base          v0.7.0-rc2          bc0fafb50f8f        5 days ago          25.51 MB
rancher/os-docker        1.12.1              ccc1cfe70218        6 weeks ago         98.19 MB
```

If I try to run the os-autoformat image:
```
[root@compute3 ~]# sudo system-docker run rancher/os-autoformat:v0.7.0-rc2
+ MAGIC='boot2docker, please format-me'
+ DEVS=(${AUTOFORMAT})
```

If I try to run the os-cloudinit image:
```
[root@compute3 ~]# sudo system-docker run rancher/os-cloudinit:v0.7.0-rc2 
system-docker: Error response from daemon: Container command '/usr/bin/ros' not found or does not exist..
```

Any ideas?

**Comment by joshwget** [comment]
@ChromoX How are you setting your cloud-config? `rancher.autoformat` is designed to be used as a kernel parameter.

**Comment by joshwget** [comment]
@bachp I confirmed that a kernel panic no longer occurs in v0.7.0-rc4. I'm going to leave this issue open since we still haven't resolved why RancherOS was unable to mount state in your case.

**Comment by ChromoX** [comment]
@joshwget You were right. Wasn't using it as a kernel parameter. Thanks!

**Comment by joshwget** [comment]
We'll probably support autoformat as part of a cloud-config at some point in the future after #1175.

**Comment by joshwget** [comment]
@bachp Can you try this on v0.7.0 when you have the chance?

**Comment by bachp** [comment]
@joshwget I retried with v0.7.0. But I'm unable to perform autoformat. I tried the instructions at: http://docs.rancher.com/os/storage/state-partition/ and I also tried adding `rancher.state.formatzero`.

I also tried to add add autoformat to cloud-init as described here: http://docs.rancher.com/os/storage/state-partition/ again without luck.

I used `wipefs -a /dev/sda` on the disk before. Also I see an "autoformat" job starting but nothing seems to happen.

**Comment by janeczku** [comment]
Same here. With 0.7.0 autoformat does not work when booting via IPXE.
Kernel params: `rancher.state.dev=LABEL=RANCHER_STATE rancher.state.autoformat=[/dev/vda]`
Couldn't find anything interesting in the debug logs other than this:

![boot](https://cloud.githubusercontent.com/assets/3813921/19990002/a258d656-a22a-11e6-956e-6e754bacf7fc.png)

**Comment by joshwget** [comment]
These seem like two separate issues. For @bachp the system is booting but autoformat isn't running.

@janeczku Do you have any other kernel parameters?

**Comment by bachp** [comment]
@joshwget  I'm also booting via iPXE. So the issue might be related to the one reported by @janeczku .
I used the parameters as described here: http://docs.rancher.com/os/running-rancheros/server/pxe/ no additional kernel args.

**Comment by janeczku** [comment]
@joshwget 

> $ cat /proc/cmdline

```
rancher.state.dev=LABEL=RANCHER_STATE rancher.state.autoformat=[/dev/vda] rancher.cloud_init.datasources=[ec2]
```

**Comment by SvenDowideit** [comment]
in my case, the new, un-formatted, new disk wasn't all zeros, so the autoformat didn't trigger. for my testing use, I think I'd like a `rancher.state.autoformat.onboot=true`

**Comment by user-name-is-taken** [comment]
I got this when I set `sudo ros config syslinux`, set the parameters, then reboot. I'd been messing with the parameters before that though.
