### ISSUE TITLE
rancheros-install -f does not partition or re-read table correctly

### ISSUE THREAD

**Issue by huslage** [rancher/os#135]
```
[rancher@rancher ~]$ sudo rancheros-install -c cloud-init -f -v v0.2.1 -d /dev/sda -t generic   
All data will be wiped from this device
Partition: true
DEVICE: /dev/sda1
Are you sure you want to continue? [yN]y+ DEVICE=/dev/sda1
+ [[ -z /dev/sda1 ]]
++ wc -l
+++ cut -d / -f3
+++ echo /dev/sda1
++ grep sda1 /proc/partitions
+ PARTITION_COUNT=1
+ '[' 1 -gt 1 ']'
+ fdisk /dev/sda1

Welcome to fdisk (util-linux 2.25.2).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.


Command (m for help): Partition type
   p   primary (1 primary, 0 extended, 3 free)
   e   extended (container for logical partitions)
Select (default p): Partition number (2-4, default 2): Value out of range.
Partition number (2-4, default 2): 
No free sectors available.

Command (m for help): 

Command (m for help): 
The partition table has been altered.
Calling ioctl() to re-read partition table.
Re-reading the partition table failed.: Invalid argument

The kernel still uses the old table. The new table will be used at the next reboot or after you run partprobe(8) or kpartx(8).
```
The script stops after this. Re-running `rancheros-install` with `/dev/sda1` gives us:

```
[root@rancher rancher]# rancheros-install -c cloud-init -v v0.2.1 -d /dev/sda1 -t generic
All data will be wiped from this device
Partition: true
DEVICE: /dev/sda1
Are you sure you want to continue? [yN]y

+ DEVICE=/dev/sda1
+ [[ -z /dev/sda1 ]]
++ wc -l
+++ echo /dev/sda1
+++ cut -d / -f3
++ grep sda1 /proc/partitions
+ PARTITION_COUNT=1
+ '[' 1 -gt 1 ']'
+ fdisk /dev/sda1

Welcome to fdisk (util-linux 2.25.2).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.

Command (m for help): Partition type
   p   primary (1 primary, 0 extended, 3 free)
   e   extended (container for logical partitions)
Select (default p): Partition number (2-4, default 2): Value out of range.
Partition number (2-4, default 2): 
No free sectors available.

Command (m for help): 

Command (m for help): 
The partition table has been altered.
Calling ioctl() to re-read partition table.
Re-reading the partition table failed.: Invalid argument

The kernel still uses the old table. The new table will be used at the next reboot or after you run partprobe(8) or kpartx(8).
```
`fdisk` shows a partition:
```
Disk /dev/sda: 17.1 GB, 17179869184 bytes
171 heads, 2 sectors/track, 98112 cylinders
Units = cylinders of 342 * 512 = 175104 bytes

   Device Boot      Start         End      Blocks  Id System
/dev/sda1               6       98113    16776192  83 Linux
```

`cloud-init` is simply my ssh keys.

**Comment by huslage** [comment]
I cleared my partition table and it worked:

```
[root@rancher rancher]# rancheros-install -c cloud-init -f -v v0.2.1 -d /dev/sda -t generic 
+ DEVICE=/dev/sda
+ [[ -z /dev/sda ]]
++ wc -l
+++ echo /dev/sda
+++ cut -d / -f3
++ grep sda /proc/partitions
+ PARTITION_COUNT=1
+ '[' 1 -gt 1 ']'
+ fdisk /dev/sda

Welcome to fdisk (util-linux 2.25.2).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.


Command (m for help): Partition type
   p   primary (0 primary, 0 extended, 4 free)
   e   extended (container for logical partitions)
Select (default p): Partition number (1-4, default 1): First sector (2048-33554431, default 2048): Last sector, +sectors or +size{K,M,G,T,P} (2048-33554431, default 33554431): 
Created a new partition 1 of type 'Linux' and of size 16 GiB.

Command (m for help): The partition table has been altered.
Calling ioctl() to re-read partition table.
Syncing disks.

udev
+ getopts c:d:t:r: OPTION
+ case $OPTION in
+ DEVICE=/dev/sda
+ getopts c:d:t:r: OPTION
+ case $OPTION in
+ ENV=generic
+ getopts c:d:t:r: OPTION
+ case $OPTION in
+ CLOUD_CONFIG=/opt/user_config.yml
+ getopts c:d:t:r: OPTION
+ BASE_DIR=/mnt/new_img
+ '[' -n generic ']'
+ case ${ENV} in
+ format_and_mount
+ device_defined /dev/sda
+ [[ -z /dev/sda ]]
+ format_device
+ mkfs.ext4 -F -L RANCHER_STATE /dev/sda1
mke2fs 1.42.12 (29-Aug-2014)
Found a dos partition table in /dev/sda1
Creating filesystem with 4194048 4k blocks and 1048576 inodes
Filesystem UUID: d9067681-bc9a-427c-9d23-362e88172f42
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208, 
	4096000

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (32768 blocks): done
Writing superblocks and filesystem accounting information: done   

+ mount_device
+ local label=RANCHER_STATE
+ mkdir -p /mnt/new_img
++ lsblk -o name
++ wc -l
++ grep RANCHER_BOOT
+ '[' 0 -eq 1 ']'
+ mount -L RANCHER_STATE /mnt/new_img
+ trap 'umount /mnt/new_img' EXIT
+ create_boot_dirs
+ mkdir -p /mnt/new_img/boot/grub
+ install_grub
+ grub-install --boot-directory=/mnt/new_img/boot /dev/sda
Installing for i386-pc platform.
grub-install: warning: Attempting to install GRUB to a disk with multiple partition labels.  This is not supported yet..
grub-install: warning: Embedding is not possible.  GRUB can only be installed in this setup by using blocklists.  However, blocklists are UNRELIABLE and their use is discouraged..
grub-install: error: will not proceed with blocklists.
+ umount /mnt/new_img
```

**Comment by huslage** [comment]
This resulted in a machine without an OS though.

**Comment by huslage** [comment]
This is a fresh vmWare Fusion instance with a new disk.

**Comment by cloudnautique** [comment]
We are working to better support cases where we fail to partition the disk correctly. rancherio/os-installer#7. We didn't want to be too aggressive out of the gate because we weren't sure what configurations users would have. But, I think this scenario is something we can address.

It looks like in the first run, you used /dev/sda1 as the -d option? the command line and script output seem to conflict a bit compared to the second run.

Looks like a label was left behind. Probably need to add better error reporting when that fails as well. If you try with a new fresh disk, does it work?

**Comment by janeczku** [comment]
I can't install it either:

```
Writing superblocks and filesystem accounting information: done   

+ mount_device
+ local label=RANCHER_STATE
+ mkdir -p /mnt/new_img
++ lsblk -o name
++ wc -l
++ grep RANCHER_BOOT
+ '[' 0 -eq 1 ']'
+ mount -L RANCHER_STATE /mnt/new_img
+ trap 'umount /mnt/new_img' EXIT
+ create_boot_dirs
+ mkdir -p /mnt/new_img/boot/grub
+ install_grub
+ grub-install --boot-directory=/mnt/new_img/boot /dev/sda
Installing for i386-pc platform.
grub-install: warning: Attempting to install GRUB to a disk with multiple partition labels.  This is not supported yet..
grub-install: warning: Embedding is not possible.  GRUB can only be installed in this setup by using blocklists.  However, blocklists are UNRELIABLE and their use is discouraged..
grub-install: error: will not proceed with blocklists.
+ umount /mnt/new_img
```

This is with a fresh disk. I don't know why GRUB complains about multiple labels. There is only one:
![screen](https://cloud.githubusercontent.com/assets/3813921/7081912/01040580-df4b-11e4-808f-e3d1d9214525.png)

**Comment by deniseschannon** [comment]
With v0.3.0, this should be fixed. If not, please reopen.

**Comment by riyaolin** [comment]
with version v0.3.1, this issue is still there. Please provide a fix

**Comment by riyaolin** [comment]
oops. It seems I downloaded the wrong .iso (machine-rancheros.iso), which caused the problem.

**Comment by fatihusta** [comment]
Hi
I testing install to disk on virtualbox but not booting system

Where is the problem?


[rancher@rancher ~]$ sudo rancheros-install -c cloud-config-processed.yml -d /dev/sda
No install type specified...defaulting to generic
All data will be wiped from this device
Partition: true
DEVICE: /dev/sda
Are you sure you want to continue? [yN]yUnable to find image 'rancher/os:v0.3.1' locally
v0.3.1: Pulling from rancher/os

39bb80489af7: Pull complete 
df2a0347c9d0: Pull complete 
4a5ef650aa62: Pull complete 
4530c6461e13: Pull complete 
68782ff9478e: Pull complete 
b6d3ec6a3d82: Pull complete 
261af237bdfc: Pull complete 
b7af9f9582a3: Already exists 
Digest: sha256:1a0e9b415b4bac08fc346cd14c454c4838686240c94d6993f4c85530114b9701
Status: Downloaded newer image for rancher/os:v0.3.1
+ DEVICE=/dev/sda
+ [[ -z /dev/sda ]]
++ wc -l
+++ cut -d / -f3
+++ echo /dev/sda
++ grep sda /proc/partitions
+ PARTITION_COUNT=1
+ '[' 1 -gt 1 ']'
+ fdisk /dev/sda

Welcome to fdisk (util-linux 2.25.2).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.


Command (m for help): Partition type
   p   primary (0 primary, 0 extended, 4 free)
   e   extended (container for logical partitions)
Select (default p): Partition number (1-4, default 1): First sector (2048-33554431, default 2048): Last sector, +sectors or +size{K,M,G,T,P} (2048-33554431, default 33554431): 
Created a new partition 1 of type 'Linux' and of size 16 GiB.

Command (m for help): The partition table has been altered.
Calling ioctl() to re-read partition table.
Syncing disks.

udev
+ getopts i:f:c:d:t:r:o:p: OPTION
+ case $OPTION in
+ DEVICE=/dev/sda
+ getopts i:f:c:d:t:r:o:p: OPTION
+ case $OPTION in
+ ENV=generic
+ getopts i:f:c:d:t:r:o:p: OPTION
+ case $OPTION in
+ CLOUD_CONFIG=/opt/user_config.yml
+ getopts i:f:c:d:t:r:o:p: OPTION
+ DIST=/dist
+ BASE_DIR=/mnt/new_img
+ PARTITION=/dev/sda1
+ KERNEL_ARGS=
+ '[' -n generic ']'
+ case ${ENV} in
+ format_and_mount
+ format_device
+ device_defined /dev/sda
+ [[ -z /dev/sda ]]
+ mkfs.ext4 -F -i 4096 -L RANCHER_STATE /dev/sda1
mke2fs 1.42.12 (29-Aug-2014)
/dev/sda1 contains a ext4 file system labelled 'RANCHER_STATE'
        last mounted on /mnt/new_img on Fri Jun 19 12:11:12 2015
Creating filesystem with 4194048 4k blocks and 4194304 inodes
Filesystem UUID: 9ad10a74-9999-448c-aacf-b43067b62315
Superblock backups stored on blocks: 
        32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208, 
        4096000

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (32768 blocks): done
Writing superblocks and filesystem accounting information: done   

+ mount_device
+ local label=RANCHER_STATE
+ local raw=false
+ mkdir -p /mnt/new_img
++ lsblk -o name
++ grep RANCHER_BOOT
++ wc -l
+ '[' 0 -eq 1 ']'
+ local 'mount_opts=-L RANCHER_STATE'
+ '[' false == true ']'
+ mount -L RANCHER_STATE /mnt/new_img
+ trap 'umount /mnt/new_img' EXIT
+ create_boot_dirs
+ mkdir -p /mnt/new_img/boot/grub
+ install_grub
+ grub-install --boot-directory=/mnt/new_img/boot /dev/sda
Installing for i386-pc platform.
grub-install: warning: Attempting to install GRUB to a disk with multiple partition labels.  This is not supported yet..
grub-install: warning: Embedding is not possible.  GRUB can only be installed in this setup by using blocklists.  However, blocklists are UNRELIABLE and their use is discouraged..
grub-install: error: will not proceed with blocklists.
+ umount /mnt/new_img
[rancher@rancher ~]$ sudo reboot
Connection to 10.34.12.128 closed by remote host.
Connection to 10.34.12.128 closed.
[~]$

**Comment by deniseschannon** [comment]
@fatihusta what is in your `cloud-config-processed.yml`? did you include a SSH key which would allow you to SSH into the box? 

You can review the docs: http://rancherio.github.io/os/docs/running-rancheros/server/install-to-disk/ to see if that will help.

**Comment by fatihusta** [comment]
yes I followed the link until the document.

I added to the ssh key configuration files.

cloud-config-processed.yml
ssh_authorized_keys:
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDSmA2HTfo526N..... fatih@master

**Comment by deniseschannon** [comment]
To confirm, did the file look like this? It needs to have the `#cloud-config` and the spacing needs to exist in the file around the dash in front of the ssh key. I just realized the spacing was missing in the docs, so have added it there.

```
#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDSmA2HTfo526N..... fatih@master
```

**Comment by fatihusta** [comment]
Hi deniseschannon

yes I am setting file creating in this way.

I've erased VirtualBox on the definition and create it again. It worked.

I tried to reproduce the same situation. But I was not successful.
I will share it here I can reproduce the error.

Thanks for your help.

Sory my bad english.

**Comment by deniseschannon** [comment]
Ok, great. If it's another issue, please re-open a new one. Thanks.

**Comment by MichaelDays** [comment]
Getting this with v0.3.3 attempting to install the fresh machine-rancher.iso into a Parallels Desktop VM. Fresh drive image gives the fdisk partition table not reread error:

````
[rancher@rancher ~]$ sudo rancheros-install -c cloud_config.yml -f -v v0.3.3 -d /dev/sda -t generic
Unable to find image 'rancher/os:v0.3.3' locally
v0.3.3: Pulling from rancher/os
64e5325c0d9d: Pull complete 
bf84c1d84a8f: Pull complete 
2fee06ebd21b: Pull complete 
f883cdbc141f: Pull complete 
3583989b6df5: Pull complete 
c5b9cd3135d4: Pull complete 
3aa1e4862bf7: Pull complete 
18a17f653f50: Already exists 
Digest: sha256:a7d233ec194d7e2796ef596ef724c7e7c1dc17504692d596dfb6ea0e62218fad
Status: Downloaded newer image for rancher/os:v0.3.3
+ DEVICE=/dev/sda
+ [[ -z /dev/sda ]]
++ wc -l
+++ echo /dev/sda
+++ cut -d / -f3
++ grep sda /proc/partitions
+ PARTITION_COUNT=1
+ '[' 1 -gt 1 ']'
+ fdisk /dev/sda

Welcome to fdisk (util-linux 2.25.2).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.


Command (m for help): Partition type
   p   primary (0 primary, 0 extended, 4 free)
   e   extended (container for logical partitions)
Select (default p): Partition number (1-4, default 1): First sector (2048-33554431, default 2048): Last sector, +sectors or +size{K,M,G,T,P} (2048-33554431, default 33554431): 
Created a new partition 1 of type 'Linux' and of size 16 GiB.

Command (m for help): Re-reading the partition table failed.: Success
The partition table has been altered.
Calling ioctl() to re-read partition table.

The kernel still uses the old table. The new table will be used at the next reboot or after you run partprobe(8) or kpartx(8).
Syncing disks.

udev
+ getopts i:f:c:d:t:r:o:p: OPTION
+ case $OPTION in
+ DEVICE=/dev/sda
+ getopts i:f:c:d:t:r:o:p: OPTION
+ case $OPTION in
+ ENV=generic
+ getopts i:f:c:d:t:r:o:p: OPTION
+ case $OPTION in
+ CLOUD_CONFIG=/opt/user_config.yml
+ getopts i:f:c:d:t:r:o:p: OPTION
+ DIST=/dist
+ BASE_DIR=/mnt/new_img
+ PARTITION=/dev/sda1
+ KERNEL_ARGS=
+ '[' -n generic ']'
+ case ${ENV} in
+ format_and_mount
+ format_device
+ device_defined /dev/sda
+ [[ -z /dev/sda ]]
+ mkfs.ext4 -F -i 4096 -L RANCHER_STATE /dev/sda1
mke2fs 1.42.12 (29-Aug-2014)
The file /dev/sda1 does not exist and no size was specified.
````

Reboot then second run gives the grub blocklists error:

````
[rancher@rancher ~]$ sudo rancheros-install -c cloud_config.yml -f -v v0.3.3 -d /dev/sda -t generic
Unable to find image 'rancher/os:v0.3.3' locally
v0.3.3: Pulling from rancher/os
64e5325c0d9d: Pull complete 
bf84c1d84a8f: Pull complete 
2fee06ebd21b: Pull complete 
f883cdbc141f: Pull complete 
3583989b6df5: Pull complete 
c5b9cd3135d4: Pull complete 
3aa1e4862bf7: Pull complete 
18a17f653f50: Already exists 
Digest: sha256:a7d233ec194d7e2796ef596ef724c7e7c1dc17504692d596dfb6ea0e62218fad
Status: Downloaded newer image for rancher/os:v0.3.3
Device /dev/sda already partitioned!
+ DEVICE=/dev/sda
+ [[ -z /dev/sda ]]
++ wc -l
+++ echo /dev/sda
+++ cut -d / -f3
++ grep sda /proc/partitions
+ PARTITION_COUNT=2
+ '[' 2 -gt 1 ']'
+ echo 'Device /dev/sda already partitioned!'
+ echo 'Checking to see if it is mounted'
+ grep -q /dev/sda /proc/mounts
Checking to see if it is mounted
++ system-docker ps -q
+ for container in '$(system-docker ps -q)'
+ system-docker exec 86730138cd1e grep -q /dev/sda /proc/mounts
+ for container in '$(system-docker ps -q)'
+ system-docker exec 58c2991db7d9 grep -q /dev/sda /proc/mounts
+ for container in '$(system-docker ps -q)'
+ system-docker exec cbfdbe594fa3 grep -q /dev/sda /proc/mounts
+ for container in '$(system-docker ps -q)'
+ system-docker exec 29b1cc49e602 grep -q /dev/sda /proc/mounts
+ for container in '$(system-docker ps -q)'
+ system-docker exec d1ed3e1fd842 grep -q /dev/sda /proc/mounts
+ for container in '$(system-docker ps -q)'
+ system-docker exec 16712c7531e1 grep -q /dev/sda /proc/mounts
+ for container in '$(system-docker ps -q)'
+ system-docker exec 64a3e2d3302b grep -q /dev/sda /proc/mounts
+ dd if=/dev/zero of=/dev/sda bs=512 count=1
1+0 records in
1+0 records out
512 bytes (512 B) copied, 0.00140019 s, 366 kB/s
+ partprobe /dev/sda
+ fdisk /dev/sda
/dev/sda: device contains a valid 'ext4' signature, it's strongly recommended to wipe the device by command wipefs(8) if this setup is unexpected to avoid possible collisions.

Welcome to fdisk (util-linux 2.25.2).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.


Device does not contain a recognized partition table.
Created a new DOS disklabel with disk identifier 0x87adc126.

Command (m for help): Partition type
   p   primary (0 primary, 0 extended, 4 free)
   e   extended (container for logical partitions)
Select (default p): Partition number (1-4, default 1): First sector (2048-33554431, default 2048): Last sector, +sectors or +size{K,M,G,T,P} (2048-33554431, default 33554431): 
Created a new partition 1 of type 'Linux' and of size 16 GiB.

Command (m for help): The partition table has been altered.
Calling ioctl() to re-read partition table.
Syncing disks.

udev
+ getopts i:f:c:d:t:r:o:p: OPTION
+ case $OPTION in
+ DEVICE=/dev/sda
+ getopts i:f:c:d:t:r:o:p: OPTION
+ case $OPTION in
+ ENV=generic
+ getopts i:f:c:d:t:r:o:p: OPTION
+ case $OPTION in
+ CLOUD_CONFIG=/opt/user_config.yml
+ getopts i:f:c:d:t:r:o:p: OPTION
+ DIST=/dist
+ BASE_DIR=/mnt/new_img
+ PARTITION=/dev/sda1
+ KERNEL_ARGS=
+ '[' -n generic ']'
+ case ${ENV} in
+ format_and_mount
+ format_device
+ device_defined /dev/sda
+ [[ -z /dev/sda ]]
+ mkfs.ext4 -F -i 4096 -L RANCHER_STATE /dev/sda1
mke2fs 1.42.12 (29-Aug-2014)
Creating filesystem with 4194048 4k blocks and 4194304 inodes
Filesystem UUID: 3f4eba49-b6c9-4e59-b72a-c9bb237c8e93
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208, 
	4096000

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (32768 blocks): done
Writing superblocks and filesystem accounting information: done   

+ mount_device
+ local label=RANCHER_STATE
+ local raw=false
+ mkdir -p /mnt/new_img
++ lsblk -o name
++ grep RANCHER_BOOT
++ wc -l
+ '[' 0 -eq 1 ']'
+ local 'mount_opts=-L RANCHER_STATE'
+ '[' false == true ']'
+ mount -L RANCHER_STATE /mnt/new_img
+ trap 'umount /mnt/new_img' EXIT
+ create_boot_dirs
+ mkdir -p /mnt/new_img/boot/grub
+ install_grub
+ grub-install --boot-directory=/mnt/new_img/boot /dev/sda
Installing for i386-pc platform.
grub-install: warning: Attempting to install GRUB to a disk with multiple partition labels.  This is not supported yet..
grub-install: warning: Embedding is not possible.  GRUB can only be installed in this setup by using blocklists.  However, blocklists are UNRELIABLE and their use is discouraged..
grub-install: error: will not proceed with blocklists.
+ umount /mnt/new_img
````

**Comment by cloudnautique** [comment]
@michaeldays I believe the machine-rancher.iso does an auto format on boot and sets up the state partition. It is meant to be use with docker machine. If you just want to install, I would use the rancher.iso image.

**Comment by MichaelDays** [comment]
Thanks @cloudnautique that did the trick. Much appreciated!

How do I report a bug with the documentation? The bare-machine install section should probably mention the iso to use. ;)

http://os.docs.rancher.com/docs/running-rancheros/server/install-to-disk/

**Comment by deniseschannon** [comment]
@MichaelDays The iso to use is referred to in this documentation page.
http://os.docs.rancher.com/docs/running-rancheros/workstation/boot-from-iso/

I've added additional information to the install to disk section in case they didn't see that page. Thanks for the feedback!

**Comment by MichaelDays** [comment]
Thanks for the tweak, @deniseschannon - much harder for me to miss now. ;)

**Comment by daankets** [comment]
Still seeing this issue with 0.3.3. Using the rancher.iso on proxmox (KVM) with a virtio disk:
*Cloud config:*
```yaml
#cloud-config
hostname: dummy
ssh_authorized_keys:
  - ssh-rsa AAAA... daankets@blackbit.be
rancher:
  network:
    interfaces:
      eth*:
        dhcp: false
      eth0:
        address: 192.168.0.100/24
        gateway: 192.168.0.1
        mtu: 1500
    dns:
      nameservers:
        - 8.8.8.8
        - 8.8.4.4
```
*Command line:*
```bash
sudo rancheros-install -c cloudconfig.yml -d /dev/vda
```
*Output:*
```bash
No install type specified...defaulting to generic
Device /dev/vda already partitioned!
Checking to see if it is mounted
+ DEVICE=/dev/vda
+ [[ -z /dev/vda ]]
++ wc -l
+++ echo /dev/vda
+++ cut -d / -f3
++ grep vda /proc/partitions
+ PARTITION_COUNT=2
+ '[' 2 -gt 1 ']'
+ echo 'Device /dev/vda already partitioned!'
+ echo 'Checking to see if it is mounted'
+ grep -q /dev/vda /proc/mounts
++ system-docker ps -q
+ for container in '$(system-docker ps -q)'
+ system-docker exec ca40f1e71368 grep -q /dev/vda /proc/mounts
+ for container in '$(system-docker ps -q)'
+ system-docker exec eaa8d2dd6f0f grep -q /dev/vda /proc/mounts
+ for container in '$(system-docker ps -q)'
+ system-docker exec 16b33b477969 grep -q /dev/vda /proc/mounts
+ for container in '$(system-docker ps -q)'
+ system-docker exec e8bf3f735cb5 grep -q /dev/vda /proc/mounts
+ for container in '$(system-docker ps -q)'
+ system-docker exec 8700905d4492 grep -q /dev/vda /proc/mounts
+ for container in '$(system-docker ps -q)'
+ system-docker exec 0bb39604735f grep -q /dev/vda /proc/mounts
+ for container in '$(system-docker ps -q)'
+ system-docker exec 8f5a80a87136 grep -q /dev/vda /proc/mounts
+ dd if=/dev/zero of=/dev/vda bs=512 count=1
1+0 records in
1+0 records out
512 bytes (512 B) copied, 0.000809998 s, 632 kB/s
+ partprobe /dev/vda
+ fdisk /dev/vda
/dev/vda: device contains a valid 'ext4' signature, it's strongly recommended to wipe the device by command wipefs(8) if this setup is unexpected to avoid possible collisions.

Welcome to fdisk (util-linux 2.25.2).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.


Device does not contain a recognized partition table.
Created a new DOS disklabel with disk identifier 0x6de42287.

Command (m for help): Partition type
   p   primary (0 primary, 0 extended, 4 free)
   e   extended (container for logical partitions)
Select (default p): Partition number (1-4, default 1): First sector (2048-33554431, default 2048): Last sector, +sectors or +size{K,M,G,T,P} (2048-33554431, default 33554431): 
Created a new partition 1 of type 'Linux' and of size 16 GiB.

Command (m for help): The partition table has been altered.
Calling ioctl() to re-read partition table.
Syncing disks.

udev
+ getopts i:f:c:d:t:r:o:p: OPTION
+ case $OPTION in
+ DEVICE=/dev/vda
+ getopts i:f:c:d:t:r:o:p: OPTION
+ case $OPTION in
+ ENV=generic
+ getopts i:f:c:d:t:r:o:p: OPTION
+ case $OPTION in
+ CLOUD_CONFIG=/opt/user_config.yml
+ getopts i:f:c:d:t:r:o:p: OPTION
+ DIST=/dist
+ BASE_DIR=/mnt/new_img
+ PARTITION=/dev/vda1
+ KERNEL_ARGS=
+ '[' -n generic ']'
+ case ${ENV} in
+ format_and_mount
+ format_device
+ device_defined /dev/vda
+ [[ -z /dev/vda ]]
+ mkfs.ext4 -F -i 4096 -L RANCHER_STATE /dev/vda1
mke2fs 1.42.12 (29-Aug-2014)
Creating filesystem with 4194048 4k blocks and 4194304 inodes
Filesystem UUID: 8b9d6bca-4b9b-4fe0-9191-68d4899720f0
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208, 
	4096000

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (32768 blocks): done
Writing superblocks and filesystem accounting information: done   

+ mount_device
+ local label=RANCHER_STATE
+ local raw=false
+ mkdir -p /mnt/new_img
++ lsblk -o name
++ grep RANCHER_BOOT
++ wc -l
+ '[' 0 -eq 1 ']'
+ local 'mount_opts=-L RANCHER_STATE'
+ '[' false == true ']'
+ mount -L RANCHER_STATE /mnt/new_img
+ trap 'umount /mnt/new_img' EXIT
+ create_boot_dirs
+ mkdir -p /mnt/new_img/boot/grub
+ install_grub
+ grub-install --boot-directory=/mnt/new_img/boot /dev/vda
Installing for i386-pc platform.
grub-install: warning: Attempting to install GRUB to a disk with multiple partition labels.  This is not supported yet..
grub-install: warning: Embedding is not possible.  GRUB can only be installed in this setup by using blocklists.  However, blocklists are UNRELIABLE and their use is discouraged..
grub-install: error: will not proceed with blocklists.
+ umount /mnt/new_img
```
*Partition labels:*
```bash
ls -l /dev/disk/by-label
total 0
lrwxrwxrwx    1 root     root            10 Aug 22 15:30 RANCHER_STATE -> ../../vda1
lrwxrwxrwx    1 root     root             9 Aug 22 15:05 RancherOS -> ../../sr0
```

**Comment by vartana** [comment]
This should be reopened. The problem is happening to me with version 0.3.3

**Comment by dardelean** [comment]
Yes, I can confirm it too, same grub error. VM in VMware Workstation on Linux.

**Comment by dardelean** [comment]
After rebooting the machine and deleting/adding a new vdisk to the machine the install worked.

**Comment by imikushin** [comment]
Repro on v0.4.0-rc8:
```
$ mkfs.ext4 /dev/sda
$ ros install -d /dev/sda
```
