### ISSUE TITLE
Boot order for cloud-config services not working (DHCP delay causes unstablility)

### ISSUE THREAD

**Issue by janeczku** [rancher/os#1904]
**RancherOS Version: (ros os version)**
v1.0.1

1. Use the following cloud-config:

```
#cloud-config
ssh_authorized_keys:
  - ssh-rsa  123
rancher:
  services_include:
    open-vm-tools: true
  services:
    service-dyndns:
      image: dockerhub.myrepo.com/services/dyndns:latest
      labels:
        io.rancher.os.scope: system
        io.rancher.os.after: console
      net: host
``` 

**Expected behaviour**

service-dyndns is started after the console

**Actual behaviour**

service-dyndns is started before the console according to the logs.

This also seems to cause this service to win a race against DHCPd writing the local nameservers to /etc/resolv.conf. As a result Docker is using the default Google DNS to resolve the repository, which fails because its not a public DNS name.

```
[10.541505] INFO[0001] [10/17] [network]: Starting
[10.546390] time="2017-06-07T15:46:26Z" level=debug msg="START: [/usr/bin/ros entrypoint udevd] in /" 
[10.566894] udevd[1]: starting version 3.2
[10.566942] udevd[1]: starting eudev-3.2
[10.590523] DEBU[0001] Rebuild values  newRebuildLabel= origRebuildLabel= outOfSync=false rebuildLabelChanged=false
[10.666823] time="2017-06-07T15:46:26Z" level=debug msg="START: [/usr/bin/ros entrypoint netconf] in /" 
[10.670019] INFO[0001] [11/17] [network]: Started 
[10.705479] time="2017-06-07T15:46:27Z" level=debug msg="START: [netconf] in /" 
[10.714023] time="2017-06-07T15:46:27Z" level=info msg="Apply Network Config" 
[10.714187] time="2017-06-07T15:46:27Z" level=debug msg="Config: &netconf.NetworkConfig{PreCmds:[]string(nil), DNS:netconf.DNSConfig{Nameservers:[]string(nil), Search:[]string(nil)}, Interfaces:map[string]netconf.InterfaceConfig{\"lo\":netconf.InterfaceConfig{Match:\"\", DHCP:false, DHCPArgs:\"\", Address:\"\", Addresses:[]string{\"127.0.0.1/8\", \"::1/128\"}, IPV4LL:false, Gateway:\"\", GatewayIpv6:\"\", MTU:0, Bridge:\"\", Bond:\"\", BondOpts:map[string]string(nil), PostUp:[]string(nil), PreUp:[]string(nil), Vlans:\"\"}, \"eth*\":netconf.InterfaceConfig{Match:\"\", DHCP:true, DHCPArgs:\"\", Address:\"\", Addresses:[]string(nil), IPV4LL:false, Gateway:\"\", GatewayIpv6:\"\", MTU:0, Bridge:\"\", Bond:\"\", BondOpts:map[string]string(nil), PostUp:[]string(nil), PreUp:[]string(nil), Vlans:\"\"}}, PostCmds:[]string(nil), HTTPProxy:\"\", HTTPSProxy:\"\", NoProxy:\"\"}" 
[10.715383] time="2017-06-07T15:46:27Z" level=info msg="Applying 127.0.0.1/8 to lo" 
[10.715513] time="2017-06-07T15:46:27Z" level=info msg="Applying ::1/128 to lo" 
[10.715634] time="2017-06-07T15:46:27Z" level=info msg="Apply Network Config RunDhcp" 
[10.715782] time="2017-06-07T15:46:27Z" level=debug msg=RunDhcp 
[10.715901] time="2017-06-07T15:46:27Z" level=info msg="Running DHCP on eth0: dhcpcd -MA4 eth0" 
[10.761547] DEBU[0001] Loaded open-vm-tools from https://raw.githubusercontent.com/rancher/os-services/v1.0.1/o/open-vm-tools.yml 
[10.762336] DEBU[0001] Using /proc/version to set rancher.environment.KERNEL_VERSION = 4.9.24-rancher 
[10.762474] DEBU[0001] Using /proc/version to set rancher.environment.KERNEL_VERSION = 4.9.24-rancher 
[10.762628] DEBU[0001] Using /proc/version to set rancher.environment.KERNEL_VERSION = 4.9.24-rancher 
[10.769237] INFO[0001] [11/18] [ntp]: Starting 
[10.769352] INFO[0001] [11/18] [open-vm-tools]: Starting
[10.770567] INFO[0001] [11/18] [service-dyndns]: Starting 
[10.823837] DEBU[0001] Rebuild values  newRebuildLabel= origRebuildLabel= outOfSync=false rebuildLabelChanged=false
[10.906008] time="2017-06-07T15:46:27Z" level=debug msg="START: [/usr/bin/ros entrypoint ntpd --nofork -g] in /" 
[10.906315] INFO[0002] [12/18] [ntp]: Started  
[10.906463] INFO[0002] [12/18] [cloud-init-execute]: Starting 
[10.959001] DEBU[0002] Rebuild values  newRebuildLabel= origRebuildLabel= outOfSync=false rebuildLabelChanged=false
[11.040162] time="2017-06-07T15:46:27Z" level=debug msg="START: [/usr/bin/ros entrypoint cloud-init-execute -pre-console] in /" 
[11.060808] time="2017-06-07T15:46:27Z" level=debug msg="START: [cloud-init-execute -pre-console] in /" 
[11.060824] time="2017-06-07T15:46:27Z" level=info msg="Running cloud-init-execute: pre-console=true, console=false" 
[11.206411] ERRO[0002] Failed to pull image dockerhub.myrepo.com/services/dyndns:latest: Error response from daemon: Get https://dockerhub.myrepo.com/v1/_ping: dial tcp: lookup dockerhub.myrepo.com on 8.8.4.4:53: server misbehaving 
[11.206848] ERRO[0002] Failed Starting service-dyndns : Error response from daemon: Get https://dockerhub.cisco.com/v1/_ping: dial tcp: lookup dockerhub.myrepo.com on 8.8.4.4:53: server misbehaving 
[11.326026] INFO[0002] [13/18] [cloud-init-execute]: Started  
[11.326178] INFO[0002] [13/18] [console]: Starting
[11.405223] DEBU[0002] Rebuild values  newRebuildLabel=always origRebuildLabel=always outOfSync=false rebuildLabelChanged=false
[11.405372] INFO[0002] Rebuilding console
[11.540496] INFO[0002] [14/18] [console]: Started 
[11.540671] INFO[0002] [14/18] [docker]: Starting 
[11.540828] INFO[0002] [14/18] [preload-user-images]: Starting
```

**Comment by janeczku** [comment]
And here is the DHCPd side of the race condition:

tail /var/log/syslog:

```
(...)
Jun  7 15:46:28 rancher dhcpcd[1023]: eth0: soliciting a DHCP lease
Jun  7 15:46:28 rancher dhcpcd[1023]: eth0: offered xx.xx.13.228 from xx.xx.49.191
Jun  7 15:46:28 rancher dhcpcd[1023]: eth0: leased xx.xx.13.228 for 3535 seconds
Jun  7 15:46:28 rancher dhcpcd[1023]: eth0: adding route to xx.xx.13.0/24
Jun  7 15:46:28 rancher dhcpcd[1023]: eth0: adding default route via xx.xx.13.1
Jun  7 15:46:28 rancher dhcpcd[1023]: forked to background, child pid 1213
(...)
```

Note: DHCP is completed at 15:46:28, which is after Docker unsuccessfully tried to pull the service-dyndns image.

**Comment by SvenDowideit** [comment]
ah, wow, this'll be "fun" to make tests for.

**Comment by forktheweb** [comment]
yeah, it's been fun trying to figure out what's causing our vms not to boot correct lol

**Comment by SvenDowideit** [comment]
ok, I'm starting to unpack this using the following cloud-config:

```
#cloud-config
rancher:
  bootstrap_docker:
    registry_mirror: "http://10.10.10.23:5555"
    insecure_registry:
    - 10.10.10.23:5000
    - arian:5000
  docker:
    registry_mirror: "http://10.10.10.23:5555"
    insecure_registry:
    - 10.10.10.23:5000
    - arian:5000
  system_docker:
    registry_mirror: "http://10.10.10.23:5555"
    insecure_registry:
    - 10.10.10.23:5000
    - arian:5000
  services:
    local-registry:
      image: registry
      labels:
        io.rancher.os.scope: system
        io.rancher.os.after: console
      ports:
      - 5000:5000
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC85w9stZyiLQp/DkVO6fqwiShYcj1ClKdtCqgHtf+PLpJkFReSFu8y21y+ev09gsSMRRrjF7yt0pUHV6zncQhVeqsZtgc5WbELY2DOYUGmRn/CCvPbXovoBrQjSorqlBmpuPwsStYLr92Xn+VVsMNSUIegHY22DphGbDKG85vrKB8HxUxGIDxFBds/uE8FhSy+xsoyT/jUZDK6pgq2HnGl6D81ViIlKecpOpWlW3B+fea99ADNyZNVvDzbHE5pcI3VRw8u59WmpWOUgT6qacNVACl8GqpBvQk8sw7O/X9DSZHCKafeD9G5k+GYbAUz92fKWrx/lOXfUXPS3+c8dRIF
```

## test1: use Docker Hub (via the registry-mirror)
works: `> INFO[0013] [17/17] [local-registry]: Started`

one observation is that the `Started` debug log line is printed after the service's image has been pulled and sucessfully "started" - this is not an indicator of the actual order :(

## test2: use registry on my network

**Comment by SvenDowideit** [comment]
## test2: use registry on my network using IP address

`image: 10.10.10.23:5000/registry`

and yup, same result - its `17/18`

## test3: use local registry with dns name

same.

so @janeczku - the issue, with the amount of detail reported, works here. I need more details.

**Comment by SvenDowideit** [comment]
mmm, after lunch I'm going to add the `open-vm-tools` bit - maybe there's something happening due to that. (mmm, and without a mirror)

**Comment by SvenDowideit** [comment]
even then, the (successfully pulled) local-registry is started after console.

So far, I'm thinking that none of the `Starting` and `Started` log output's tell us anything about actual start order - because the ordering is a loose cfg - if that container takes longer to start, the next will have already started.

Its worth changing your local registry from a hostname to an IP address to test if successful and fast pulling results in the order you expect...

At this point, this issue appears to be a continuation of the DHCP DNS setting problem - and hopefully not a libcompose issue. (but if you can give me more info...)

**Comment by SvenDowideit** [comment]
@forktheweb @janeczku the other thing is to set the DNS from our cmdline / os-config - as you obviously can't rely on your DHCP server to answer in a timely way.

**Comment by forktheweb** [comment]
@SvenDowideit   Jan and I were talking about this and because it's an intermittent issue we're wondering if there's any way we could possibly pass a parameter or something that would extend the DHCP timeout?   Because I think what's happening is the DHCP container has a race condition and it's defaulting.  This might be a stop-gap until we can find a better way to deal with it.  Right now we can pass the DNS into the cloud-config but only for certain data centers, and because those change this is only a temporary solution.

**Comment by SvenDowideit** [comment]
we've added the `dhcpcd --wait` option in 1.0.3, and so far, it seems to have resolve the ordering problem.

**Comment by SvenDowideit** [comment]
#1921 seems to make a huge difference to this issue.

I'll be backporting it to 1.0.4

**Comment by SvenDowideit** [comment]
the DHCP wait change in https://github.com/rancher/os/pull/2021 should fix the problem

**Comment by AleksandrNull** [comment]
I'm still struggling with dhcp. Wait doesn't help a lot because if by some reason dhcp process will return 1 it will continue to run next services.  So, container with dhcp will run client again but cloud-init already gone.
`[   53.517504] time="2017-08-12T19:24:20Z" level=info msg="Apply Network Config RunDhcp" 
[   53.517899] time="2017-08-12T19:24:20Z" level=debug msg="RunDhcp(%!V(bool=true), true)" 
[   53.518724] time="2017-08-12T19:24:20Z" level=info msg="Running DHCP on eth0: dhcpcd -MA4 -e force_hostname=true -w --debug eth0" 
[   53.534456] time="2017-08-12T19:24:20Z" level=error msg="exit status 1" 
[   53.534698] time="2017-08-12T19:24:20Z" level=debug msg="dhcpcd -u eth1: " 
[   53.711763] time="2017-08-12T19:24:20Z" level=debug msg="START: [/usr/bin/ros entrypoint /bin/start_ntp.sh] in /" 
`

**Comment by albertdb** [comment]
The bug reported by @AleksandrNull is still present in 1.3.0 (and I guess 1.4.0).

The VM seems to somehow get an IP assigned, but `/etc/resolv.conf` does't contain any nameserver.

This happens frequently.

**Comment by niusmallnan** [comment]
@kingsd041 Can you please help to reproduce and confirm when you have time?

**Comment by albertdb** [comment]
I'm afraid that the bug is more serious than expected. On a VM with several network interfaces, sometimes one of the interfaces doesn't get an IP (dhcpd exit status 1), having to reboot the machine o manually launch dhcp.  This never ever happened in v0.4.3.

**Comment by niusmallnan** [comment]
We use dhcpcd to manage the networking in ROS, when dhcpcd is operating on more than one interface, it is called Master mode.

If there is only one network interface, `dhcpcd wait` is useful.  It can wait for an address to be assigned before forking to the background.

If there is more than one network interface, such as eth0 and eth1, ROS will run the following commands:
```
dhcpcd -MA4 -e force_hostname=true -w --debug eth0
dhcpcd -MA4 -e force_hostname=true -w --debug eth1
```
Assuming `dhcpcd eth0` becomes the master process, eth1 does not wait for the IP, but returns the following information directly:
```
sending commands to master dhcpcd process
send ok
```
Then we can see logs like `exit status 1` in the ROS logs.
If running the /etc/resolve.conf configuration or the custom service are not what you expect, then probably because of a network interface they depend on, it happens to be not in Master mode, then there will be problems.

**Comment by albertdb** [comment]
Hi,

The explanation seems logical, but in our experience it doesn't work that way. Every time we see a `dhcpd exit status 1`, the corresponding interface doesn't get an IP, and we don't see the `sending commands to master dhcpcd process` log trace. In fact, when dhcpcd does that, its exit code is 0, not 1.
```
[rancher@host-10-127-2-221 ~]$ sudo dhcpcd -MA4 -e force_hostname=true -w --debug 
sending commands to master dhcpcd process
send OK
[rancher@host-10-127-2-221 ~]$ echo $?
0
```
We kind of solved this issue putting `dhcpcd` command in `/etc/rc.local', but that's an ugly patch.

Maybe sometimes there's a race condition between the different `dhcpcd`  trying to be the master. Maybe sequentializing them or, even better, launching `dhcpcd` without specifying any interface (if all interfaces are set in config to use DHCP) would solve the issue nicely.

Thanks

**Comment by niusmallnan** [comment]
@albertdb You can see more dhcpcd logs in syslog:
```
cat /var/log/syslog | grep dhcpcd
```
Some logs will be saved to stdout and stderr.

**Comment by niusmallnan** [comment]
Currently limited for the following reasons, this problem cannot be solved perfectly:
1. The service labels `io.rancher.os.after` and `io.rancher.os.before`, they just control the startup order of the containers. This is the limit of docker-compose.
2. If using multiple NICs, dhcpcd wait is only useful for the first NIC.
If you use DHCP, and dhcp response is not fast enough, there will be a race condition. 

I think we can avoid this problem in the following way.
```
#cloud-config
rancher:
write_files:
  - path: /etc/rc.local
    permissions: "0755"
    owner: root
    content: |
      #!/bin/bash
      # wait for network
      while ! curl -o /dev/null -sf https://hub.docker.com/; do
        echo "wait network up"
      done

      # run on user-docker
      wait-for-docker
      docker run xxxx

      # run on system-docker
      system-docker run xxxx

      # run service
      ros service up xxx
```

I just keep this issue open, currently no good solution.

**Comment by till** [comment]
@niusmallnan That seems to be a total hack. :(

Can you try to "fix" this failure?
https://github.com/rancher/os/issues/2560#issuecomment-441055533

(The one where the error is not captured because of some mis-use of the logger. At least that is what I am thinking.)

Then I would continue to load test this. In the meantime, we moved our k8s to ubuntu nodes as this happens frequently.
