### ISSUE TITLE
Rancher for VMWare downgrades Docker Version automatically

### ISSUE THREAD

**Issue by ThunderRush** [rancher/os#2710]
**RancherOS Version: (ros os version)**
1.5.1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
vSphere

When I deploy a new rancher cluster via the GUI (Both Settings and Node Template use  https://releases.rancher.com/os/v1.5.1/vmware/rancheros-autoformat.iso), the node starts up correctly with Docker Version 18.06.01-ce. But as the cluster is being deployed, it switches back to 17.03.2-ce, no matter what I do.

I have no setting in my cloud config file.

**Comment by ThunderRush** [comment]
Something is appearently switching the docker at some point during the cluster deployment process.

`./syslog:Mar 12 15:49:28 rancher sudo:   docker : TTY=unknown ; PWD=/home/docker ; USER=root ; COMMAND=/usr/bin/sh -c sleep 3; ros engine switch -f docker-17.03.2-ce`

I have no also tried to supply the docker version in the cloud-config with equally little success.

`rancher:
  docker:
    engine: docker-18.06.1-ce`

**Comment by niusmallnan** [comment]
There is a setting in Rancher UI, which is named `engine-install-url`. @ThunderRush

**Comment by ThunderRush** [comment]
Thank you, but I have checked that already. It is set to

`https://releases.rancher.com/install-docker/18.09.sh`

Furthmore, I thought this engine-install-url does not apply to the vSphere Node Driver?

**Comment by ThunderRush** [comment]
After a bit more digging I have found the following things:
Right after I deployed the node (with the + on the Rancher GUI) I SSH'd onto it once again. After boot, it had the right docker version:

```
[rancher@rancher ~]$ sudo ros engine list
...
enabled  docker-18.06.1-ce
```

However, then following error appeared on STDOUT:

`WARN[0000] Failed to detect current docker: Error: No such container: docker`

A few seconds later the version was switched:

```
[rancher@rancher ~]$ sudo ros engine list
...
enabled  docker-17.03.2-ce
```

In `syslog`, following can be found again:

`Mar 21 14:14:58 rancher sudo:  rancher : TTY=pts/0 ; PWD=/home/rancher ; USER=root ; COMMAND=/bin/ros engine list
time="2019-03-21T14:14:07.623191763Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Mar 21 14:14:58 rancher sudo:   docker : TTY=unknown ; PWD=/home/docker ; USER=root ; COMMAND=/usr/bin/sh -c sleep 3; ros engine switch -f docker-17.03.2-ce
Mar 21 14:14:59 rancher sudo:  rancher : TTY=pts/0 ; PWD=/home/rancher ; USER=root ; COMMAND=/bin/ros engine list
Mar 21 14:15:00 rancher sudo:  rancher : TTY=pts/0 ; PWD=/home/rancher ; USER=root ; COMMAND=/bin/ros engine list
`

This is what appears in `docker.log` around the same time, with quite a bit of sweet FA happening between 14:07 and 15:02

`time="2019-03-21T14:14:07.623223333Z" level=info msg="ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/docker-containerd.sock 0  <nil>}]" module=grpc
time="2019-03-21T14:14:07.623238557Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
time="2019-03-21T14:14:07.623282597Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc420167750, CONNECTING" module=grpc
time="2019-03-21T14:14:07.623481554Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc420167750, READY" module=grpc
time="2019-03-21T14:14:07.671666531Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
time="2019-03-21T14:14:07.672405903Z" level=info msg="parsed scheme: \"unix\"" module=grpc
time="2019-03-21T14:14:07.672419523Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
time="2019-03-21T14:14:07.672451219Z" level=info msg="ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/docker-containerd.sock 0  <nil>}]" module=grpc
time="2019-03-21T14:14:07.672460784Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
time="2019-03-21T14:14:07.672498739Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc42035eb60, CONNECTING" module=grpc
time="2019-03-21T14:14:07.672632245Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc42035eb60, READY" module=grpc
time="2019-03-21T14:14:07.672648026Z" level=info msg="Loading containers: start."
time="2019-03-21T14:14:07.838300753Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
time="2019-03-21T14:14:07.896747008Z" level=info msg="Loading containers: done."
time="2019-03-21T14:14:08.554123361Z" level=info msg="Docker daemon" commit=e68fc7a graphdriver(s)=overlay2 version=18.06.1-ce
time="2019-03-21T14:14:08.554611578Z" level=info msg="Daemon has completed initialization"
time="2019-03-21T14:14:08.622954750Z" level=warning msg="Could not register builder git source: failed to find git binary: exec: \"git\": executable file not found in $PATH"
time="2019-03-21T14:14:08.628978316Z" level=info msg="API listen on /var/run/docker.sock"
time="2019-03-21T14:15:02.137496601Z" level=info msg="Processing signal 'terminated'"
time="2019-03-21T14:15:02.139138250Z" level=info msg="stopping event stream following graceful shutdown" error="context canceled" module=libcontainerd namespace=moby
time="2019-03-21T14:15:02.139146206Z" level=info msg="stopping healthcheck following graceful shutdown" module=libcontainerd
time="2019-03-21T14:15:02.139180426Z" level=info msg="stopping event stream following graceful shutdown" error="context canceled" module=libcontainerd namespace=plugins.moby
time="2019-03-21T14:15:02.139758018Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc42035eb60, TRANSIENT_FAILURE" module=grpc
time="2019-03-21T14:15:02.139776217Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc42035eb60, CONNECTING" module=grpc
time="2019-03-21T14:15:02.139758321Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc420167750, TRANSIENT_FAILURE" module=grpc
time="2019-03-21T14:15:02.139790391Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc420167750, CONNECTING" module=grpc
time="2019-03-21T14:15:14.280277101Z" level=info msg="libcontainerd: new containerd process, pid: 2658"
time="2019-03-21T14:15:15.303569865Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
time="2019-03-21T14:15:15.304316025Z" level=info msg="Loading containers: start."
`

**Comment by kingsd041** [comment]
@ThunderRush This is a rancher bug, see https://github.com/rancher/rancher/issues/19141. The modified `engine-install-url` does not take effect in the vSphere node template.
Before rancher didn't fix the issue, you can modify `engineInstallURL` in v3/nodeTemplates/, like this:
```
{
...
"engineInstallURL": "http://192.168.1.69/ros/install-docker.sh",
...
```
I have verified that it works fine in my environment.

**Comment by ThunderRush** [comment]
When I try it with 
`https://releases.rancher.com/install-docker/18.09.sh`
I get the following error:
`Error creating machine: Error running provisioning: error selecting docker: (ssh command error:`

Does it need to be local?

**Comment by kingsd041** [comment]
@ThunderRush 
No need to be local.
Which docker version do you want to use?

**Comment by ThunderRush** [comment]
@kingsd041 
I tried it both with 18.09 and 18.06 now (I want 18.06)
The way I did is add the link to a nodetemplate via the API:

```...
"engineEnv": { },
"engineInsecureRegistry": null,
"engineInstallURL": "https://releases.rancher.com/install-docker/18.06.sh",
"engineLabel": { },
"engineOpt": { },
...```

The error I get out of the rancher log is this with 18.06
`2019/03/26 07:09:00 [ERROR] NodeController c-wrlpz/m-tghst [node-controller] failed with : Error creating machine: Error running provisioning: error selecting docker: (ssh command error:`

**Comment by kingsd041** [comment]
@ThunderRush  I reproduce this problem and I will fix it as soon as possible.

**Comment by kingsd041** [comment]
@ThunderRush 
I found the cause of the problem, because rancheros-autoformat.iso will cache some os-server files in `/var/lib/rancher/cache/`. The cached files do not contain `18.06.3` and `18.09. 3`, so it will fail when switching engine.
To temporarily solve this problem, you can add the following configuration to [write-files](https://rancher.com/docs/os/v1.x/en/installation/configuration/write-files/) and then set the `Cloud Init` of the vSphere host template.
```
#cloud-config
write_files:
  - path: /etc/rc.local
    permissions: "0755"
    owner: root
    content: |
      #!/bin/bash
      rm -rf /var/lib/rancher/cache/*
```

**Comment by kingsd041** [comment]
@ThunderRush 
I found the cause of the problem, because rancheros-autoformat.iso will cache some os-server files in `/var/lib/rancher/cache/`. The cached files do not contain `18.06.3` and `18.09. 3`, so it will fail when switching engine.
To temporarily solve this problem, you can add the following configuration to [write-files](https://rancher.com/docs/os/v1.x/en/installation/configuration/write-files/) and then set the `Cloud Init` of the vSphere host template.
```
#cloud-config
write_files:
  - path: /etc/rc.local
    permissions: "0755"
    owner: root
    content: |
      #!/bin/bash
      rm -rf /var/lib/rancher/cache/*
```

**Comment by ThunderRush** [comment]
@kingsd041 
Can confirm, it works with this workaround, at least with 18.06; haven't tried .09 yet.
Any information I can provide to help you fix the actual issue?

**Comment by kingsd041** [comment]
This workaround also works for 18.09, I just verified it.
@ThunderRush Thank you for your prompt answer

**Comment by MaxDiOrio** [comment]
The standard rancheros-vmware.iso appears to do the same thing as well.

**Comment by kingsd041** [comment]
Yes, we cached os-services/index.yml in the `/var/lib/rancher/cache` directory of rancheros-vmware.iso, and the cache does not contain the latest docker version, which is the root cause.

**Comment by ernst-at-tv2** [comment]
as @MaxDiOrio mentioned it's still an issue, any word on when this'll be fixed?

**Comment by kingsd041** [comment]
@ernst-at-tv2  Will be fixed in the next version, maybe v1.6.0

**Comment by claflico** [comment]
Just now getting started experimenting with Rancher 2.2.4 on vSphere using Rancheros and have been dealing with this exact issue all morning. Using rancheros-vmware.iso v1.5.2 it keeps switching back to docker-17.03.2-ce even though I have specified 18.09.02 in my cloud-config file.

I have added the above workaround to my cloud-config file but it still switches back to 17.03.2.

I know that the cloud-config is working because it is adding ssh keys to the VM.

**Comment by niusmallnan** [comment]
@claflico Rancher 2.2.4 has a known issue, which can force to set the `engine-install-url` to `17.03.sh`. 
You can try `v2.3.0-alpha5`, it can switch `engine-install-url` on UI.

**Comment by claflico** [comment]
problem persists with v2.2.5 using ros 1.5.2 & ros 1.5.3

@niusmallnan just spun up a cluster using v2.3.0-alpha5 & ros 1.5.3 and it still is installing 17.03.02

engine-install-url is set to https://releases.rancher.com/install-docker/18.09.sh

**Comment by eliaoggian** [comment]
> problem persists with v2.2.5 using ros 1.5.2 & ros 1.5.3
> 
> @niusmallnan just spun up a cluster using v2.3.0-alpha5 & ros 1.5.3 and it still is installing 17.03.02
> 
> engine-install-url is set to https://releases.rancher.com/install-docker/18.09.sh
> 
> EDIT: Setting the "Docker Install URL" to 18.09 under "Engine Options" in the vsphere node template did make it install 18.09.7 rather than the 18.09.2 that I have specified in the cloud-config file.

I tried your workaround but the node provisioning fails with `"Error creating machine: Error running provisioning: Unable to verify the Docker daemon is listening: Maximum number of retries (10) exceeded" `and, in fact, the docker daemon is not running on the node. 

I am using ROS v1.5.4 on Rancher v2.2.6
