### ISSUE TITLE
ipxe with v0.4.4 is broken and needs to be fixed

### ISSUE THREAD

**Issue by kpostrup** [rancher/os#459]
Hello,

I have tried this on a KVM virtual machine, as well on a number of different bare-metal servers.

I am booting RancherOS using iPXE as per the instructions here: http://docs.rancher.com/os/running-rancheros/server/ipxe/

With the following iPXE configuration
```
kernel http://releases.rancher.com/os/v0.3.3/vmlinuz rancher.cloud_init.datasources=[url:http://domain.tld/configs/cloud-config]
initrd http://releases.rancher.com/os/v0.3.3/initrd
boot
```
But without formatting /dev/sda, providing an URL to a cloud-config containing my ssh public key.

Contents of `cloud_config.yml`
```yaml
#cloud-config
hostname: rancher01
ssh_authorized_keys:
  - ssh-rsa AAA.. my@user
```

Installing RancherOS on 
```
rancheros-install -c /root/cloud_config.yml -d /dev/sda -f
```

When booting the installed RancherOS, I get stuck at the following point, there is no prompt or logging output.
![image](https://cloud.githubusercontent.com/assets/5655231/9009853/02c538ba-37a4-11e5-9ff2-d6cbf60952ec.png)

**Comment by kpostrup** [comment]
It is worth mentioning that I had the same problem, after installing RancherOS when booting from the ISO image.

**Comment by wmark** [comment]
I can reproduce this on VPS from Vultr in SFO and AUS.

**Comment by wmark** [comment]
@kpostrup At least for this is fixed in v0.3.4-dev. For you, too?

```bash
sudo rancheros-install -c /home/rancher/cloud-config.yml -d /dev/vda -v v0.3.4-dev

```

**Comment by janeczku** [comment]
@kpostrup if you still have this problem, enable debugging in the kernel line to get a more verbose output on boot.
```
kernel http://releases.rancher.com/os/v0.3.3/vmlinuz rancher.debug=true rancher.cloud_init.datasources=[url:http://domain.tld/configs/cloud-config]
initrd http://releases.rancher.com/os/v0.3.3/initrd
boot
```

**Comment by JamesBarwell** [comment]
I'm encountering the same issue using ISO v0.3.3, and running on Hyper-V 2012 R2 with a generation 1 VM.
```sudo rancheros-install -c cloud-config.yml -d /dev/sda -t generic```

and I still encounter the same issue after trying again with:
```sudo rancheros-install -c cloud-config.yml -d /dev/sda -t generic -v v0.3.4-dev```

I've swapped the network adaptor out for the legacy one but to no avail. Sorry, I'm not sure how to get any useful kernel debugging out of Hyper-V.

I have been able to work around this by installing an older version:
```sudo rancheros-install -c cloud-config.yml -d /dev/sda -t generic -v v0.3.0```
I still see the same error message during boot:
```9pnet: Could not find request transport: virtio```
however the network does come up and I am able to SSH into the host.

**Comment by JamesBarwell** [comment]
Just an update to say that we've not encountered this issue with any of the v0.4.x releases.

**Comment by imikushin** [comment]
This is most probably due to failing in attempt to parse an incorrect cloud-config provided at install time. Looks like it's a duplicate of #389

**Comment by 2devnull** [comment]
I didn't realize #389 was closed when I added my info yesterday, but this issue is still occurring. How can we work around it for now until a fix is in place?

**Comment by taketnoi** [comment]
+1 for this issue

**Comment by sjkeerthi** [comment]
+1

**Comment by deniseschannon** [comment]
Looking back at this thread, it doesn't look like people are having issues with the v0.4.x releases. if someone has issues with v0.4.5 (latest release), please open a new issue.
